### ISSUE TITLE
Extra +s are being appended to formData's strings

### ISSUE THREAD

**Issue by tristan-f-r** [auth70/bodyguard#1]
When sending in formData with some structure as `{ key: "this is a test" }`, all of the spaces in the string are replaced with + after being processed.

**Comment by miunau** [comment]
Hi! Sorry this took a while! You can now pass `convertPluses: true` as a config option to `form` and `softForm` to enable this behaviour for urlencoded forms. Otherwise if it's default as true, it would interfer with actual plus signs. If you want to avoid this altogether you can use `enctype="multipart/form-data"` in your form which will encode strings properly.

**Comment by tristan-f-r** [comment]
Thanks!

**Comment by miunau** [comment]
No prob :) I also added file upload support in 1.5.0
